import { StyleSheet, Platform } from 'react-native';
import { Colors } from 'constants/Colors';
import Fonts from 'constants/fonts';
import {
  Spacing,
  BorderRadius,
  ResponsiveFontSizes,
  IconSizes,
  Layout,
  moderateScale,
} from 'constants/dimensions';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: Colors.light.background,
  },
  headerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: Spacing.m,
    paddingTop: Platform.OS === 'ios' ? Spacing.s : Spacing.s + Spacing.xs,
    paddingBottom: Spacing.s,
    borderBottomWidth: 1,
    borderBottomColor: Colors.light.divider,
    backgroundColor: Colors.light.background,
  },
  backButton: {
    padding: Spacing.xs,
  },
  title: {
    fontSize: ResponsiveFontSizes.header3,
    fontWeight: Fonts.weights.bold,
    textAlign: 'center',
    flex: 1,
    color: Colors.light.text,
  },
  headerSpacer: {
    width: IconSizes.xl,
    height: IconSizes.xl,
  },
  container: {
    flex: 1,
  },
  contentContainer: {
    padding: Spacing.l,
  },
  input: {
    width: '100%',
    height: Layout.inputHeight,
    borderColor: Colors.light.border,
    borderWidth: 1,
    borderRadius: BorderRadius.m,
    paddingHorizontal: Spacing.m,
    marginBottom: Spacing.l,
    fontSize: ResponsiveFontSizes.subtitle,
    color: Colors.light.text,
    backgroundColor: Colors.light.backgroundLight,
  },
  sectionTitle: {
    fontSize: ResponsiveFontSizes.title,
    fontWeight: Fonts.weights.semiBold,
    alignSelf: 'flex-start',
    marginBottom: Spacing.m,
    color: Colors.light.text,
  },
  contactSelectorPlaceholder: {
    width: '100%',
    minHeight: moderateScale(150),
    borderColor: Colors.light.divider,
    borderWidth: 1,
    borderRadius: BorderRadius.m,
    padding: Spacing.m,
    marginBottom: Spacing.xl,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: Colors.light.backgroundPaper,
  },
  contactSelectorText: {
    color: Colors.light.textSecondary,
    textAlign: 'center',
    marginBottom: Spacing.m,
    fontSize: ResponsiveFontSizes.body,
  },
  buttonsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    width: '100%',
    marginTop: Spacing.l,
  },

  pickerInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
    height: Layout.inputHeight,
    borderColor: Colors.light.border,
    borderWidth: 1,
    borderRadius: BorderRadius.m,
    paddingHorizontal: Spacing.m,
    marginBottom: Spacing.l,
    backgroundColor: Colors.light.background,
  },
  pickerInputText: {
    fontSize: ResponsiveFontSizes.body,
    color: Colors.light.text,
  },
  pickerInputIcon: {
    marginLeft: Spacing.s,
  },
  picker: {
    width: '100%',
    backgroundColor: Colors.light.backgroundPaper,
    color: Colors.light.text,
  },
  iconPickerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: Spacing.l,
    paddingVertical: Spacing.s,
    paddingHorizontal: Spacing.xs,
    borderColor: Colors.light.border,
    borderWidth: 1,
    borderRadius: BorderRadius.m,
    width: '100%',
    height: Layout.inputHeight,
    backgroundColor: Colors.light.background,
  },
  selectedIconPreview: {
    marginRight: Spacing.m,
    padding: Spacing.xs,
  },
  errorText: {
    color: Colors.light.error,
    textAlign: 'center',
    marginVertical: Spacing.m,
    fontSize: ResponsiveFontSizes.body,
  },
  modalOverlay: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: 'rgba(0,0,0,0.5)',
  },
  modalContent: {
    backgroundColor: Colors.light.backgroundPaper,
    borderTopLeftRadius: BorderRadius.l,
    borderTopRightRadius: BorderRadius.l,
    padding: Spacing.m,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingBottom: Spacing.m,
    borderBottomWidth: 1,
    borderBottomColor: Colors.light.divider,
  },
  modalTitle: {
    fontSize: ResponsiveFontSizes.title,
    fontWeight: Fonts.weights.semiBold,
    color: Colors.light.text,
  },
  modalDoneButton: {
    fontSize: ResponsiveFontSizes.body,
    color: Colors.light.primary,
    fontWeight: Fonts.weights.medium,
  },
});
