import { StyleSheet } from 'react-native';
import { Colors } from 'constants/Colors';
import Fonts from 'constants/fonts';
import {
  Spacing,
  BorderRadius,
  IconSizes,
  ResponsiveFontSizes,
  Layout,
  moderateScale,
  isTablet,
} from 'constants/dimensions';

export const createHomeStyles = (theme: typeof Colors.light) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.backgroundLight,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: isTablet() ? Spacing.l : Spacing.m,
    backgroundColor: theme.backgroundLight,
    borderTopColor: theme.icon,
  },
  kinshipText: {
    fontSize: isTablet() ? ResponsiveFontSizes.header1 : ResponsiveFontSizes.header2,
    fontWeight: Fonts.weights.medium,
    fontFamily: Fonts.headerBold,
    color: theme.tint,
  },
  headerIcons: {
    flexDirection: 'row',
  },
  headerIcon: {
    marginLeft: isTablet() ? Spacing.m : Spacing.s,
    height: isTablet() ? IconSizes.xxl : IconSizes.xl,
    width: isTablet() ? IconSizes.xxl : IconSizes.xl,
    paddingLeft: Spacing.xxs,
    justifyContent: 'center',
    alignItems: 'center',
  },
  notificationIconContainer: {
    position: 'relative',
    justifyContent: 'center',
    alignItems: 'center',
  },
  notificationBadge: {
    position: 'absolute',
    top: -5,
    right: -5,
    backgroundColor: theme.error,
    borderRadius: BorderRadius.round,
    minWidth: moderateScale(18),
    height: moderateScale(18),
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: Spacing.xxs,
  },
  notificationBadgeText: {
    color: theme.primaryContrastText,
    fontSize: ResponsiveFontSizes.caption,
    fontWeight: Fonts.weights.bold,
  },
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme.neutralBg,
    borderWidth: 1,
    borderColor: theme.icon,
    borderRadius: BorderRadius.round,
    paddingHorizontal: isTablet() ? Spacing.m : Spacing.s,
    marginTop: isTablet() ? Spacing.l : Spacing.m,
    marginBottom: isTablet() ? Spacing.m : Spacing.s,
    height: isTablet() ? Layout.SCREEN_HEIGHT * 0.07 : Layout.SCREEN_HEIGHT * 0.055,
  },
  searchIcon: {
    marginRight: Spacing.s,
    fontSize: isTablet() ? 28 : 24,
  },
  searchInput: {
    flex: 1,
    paddingVertical: 0,
    fontSize: ResponsiveFontSizes.header2,
    color: theme.text,
  },
  dashboardContent: {
    flex: 1,
  },
  dashboardTitle: {
    fontSize: ResponsiveFontSizes.header3,
    fontWeight: Fonts.weights.medium,
    marginBottom: Spacing.m,
    fontFamily: Fonts.headerSemiBold,
    marginHorizontal: Layout.SCREEN_WIDTH * 0.06,
    color: theme.textDarkContrast,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: Spacing.s,
  },
  recentActivityHeader: {
    marginTop: Spacing.s,
  },
  section: {
    backgroundColor: theme.background,
    paddingHorizontal: Spacing.m,
    paddingVertical: Spacing.s,
    borderRadius: BorderRadius.m,
    marginBottom: Spacing.m,
  },
  sectionTitle: {
    fontSize: ResponsiveFontSizes.title,
    fontWeight: Fonts.weights.medium,
    color: theme.textDarkContrast,
  },
  seeAllText: {
    color: theme.accent,
    fontSize: ResponsiveFontSizes.body,
  },
  eventItem: {
    flexDirection: 'row',
    backgroundColor: theme.backgroundLight,
    borderRadius: BorderRadius.m,
    padding: Spacing.m,
    marginBottom: Spacing.s,
    shadowColor: theme.text,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 1,
    elevation: 2,
  },
  eventDate: {
    marginRight: Spacing.m,
    alignItems: 'center',
    width: moderateScale(60),
    height: moderateScale(60),
    borderRadius: BorderRadius.s,
    justifyContent: 'center',
  },
  eventMonth: {
    fontSize: ResponsiveFontSizes.caption,
    fontWeight: 'bold',
  },
  eventDay: {
    fontSize: ResponsiveFontSizes.header2,
    fontWeight: 'bold',
  },
  eventDetails: {
    flex: 1,
  },
  eventTitle: {
    fontSize: ResponsiveFontSizes.subtitle,
    fontWeight: Fonts.weights.medium,
    marginBottom: Spacing.xs,
    color: theme.textDarkContrast,
  },
  eventTimeLocation: {
    flexDirection: 'column',
  },
  eventTime: {
    fontSize: ResponsiveFontSizes.body,
    color: theme.icon,
    marginLeft: Spacing.xs,
  },
  eventLocation: {
    fontSize: ResponsiveFontSizes.body,
    color: theme.icon,
    marginLeft: Spacing.xs,
  },
  activityItemCard: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: Spacing.m,
    borderRadius: BorderRadius.m,
    marginBottom: Spacing.s,
    shadowColor: theme.text,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 3,
  },
  activityIconCircle: {
    width: moderateScale(44),
    height: moderateScale(44),
    borderRadius: moderateScale(22),
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: Spacing.m,
  },
  activityTextContainer: {
    flex: 1,
    justifyContent: 'center',
  },
  activityDescriptionText: {
    fontSize: ResponsiveFontSizes.body,
    fontFamily: Fonts.bodyRegular,
    color: theme.text,
    marginBottom: Spacing.xxs,
  },
  activityTimeText: {
    fontSize: ResponsiveFontSizes.caption,
    fontFamily: Fonts.captionRegular,
    color: theme.textSecondary,
  },
  proFeatureContent: {
    alignItems: 'center',
    paddingVertical: Spacing.l,
    backgroundColor: theme.backgroundSecondary,
    borderRadius: BorderRadius.m,
    marginTop: Spacing.s,
  },
  proFeatureText: {
    fontSize: ResponsiveFontSizes.subtitle,
    color: theme.textDarkContrast,
    textAlign: 'center',
    marginTop: Spacing.s,
    marginBottom: Spacing.s,
    paddingHorizontal: Spacing.s,
  },
  mockChart: {
    fontSize: ResponsiveFontSizes.body,
    color: theme.text,
    padding: Spacing.m,
    backgroundColor: theme.backgroundLight,
    borderWidth: 1,
    borderColor: theme.icon,
    borderRadius: BorderRadius.s,
    textAlign: 'center',
    width: '80%',
  },
  upgradePrompt: {
    alignItems: 'center',
    paddingVertical: Spacing.l,
    backgroundColor: theme.backgroundLight,
    borderRadius: BorderRadius.m,
    marginTop: Spacing.s,
    borderWidth: 1,
    borderColor: theme.icon,
  },
  upgradeText: {
    fontSize: ResponsiveFontSizes.subtitle,
    color: theme.textDarkContrast,
    textAlign: 'center',
    marginTop: Spacing.s,
    marginBottom: Spacing.m,
    paddingHorizontal: Spacing.s,
  },
  upgradeButton: {
    backgroundColor: theme.accent,
    paddingVertical: Spacing.s,
    paddingHorizontal: Spacing.l,
    borderRadius: BorderRadius.l,
  },
  upgradeButtonText: {
    color: theme.neutralBg,
    fontSize: ResponsiveFontSizes.body,
    fontWeight: 'bold',
  },
  adPlaceholderBanner: {
    height: moderateScale(50),
    backgroundColor: theme.backgroundLight,
    justifyContent: 'center',
    alignItems: 'center',
    borderTopWidth: 1,
    borderColor: theme.icon,
  },
  adPlaceholderText: {
    color: theme.icon,
    fontSize: ResponsiveFontSizes.caption,
  },
  noItemsText: {
    textAlign: 'center',
    color: theme.icon,
    marginTop: Spacing.m,
    fontSize: ResponsiveFontSizes.body,
  },
  errorText: {
    textAlign: 'center',
    color: theme.error,
    marginTop: Spacing.m,
    fontSize: ResponsiveFontSizes.body,
    paddingHorizontal: Spacing.l,
  },
  activityActions: {
    marginTop: 8,
    flexDirection: 'column',
  },
  actionButtonRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  actionButton: {
    backgroundColor: theme.primary,
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 4,
    alignItems: 'center',
    marginTop: 4,
  },
  acceptButton: {
    backgroundColor: theme.success,
    flex: 1,
    marginRight: 4,
  },
  declineButton: {
    backgroundColor: theme.error,
    flex: 1,
    marginLeft: 4,
  },
  actionButtonText: {
    color: 'white',
    fontSize: 12,
    fontWeight: '500',
  },
  highPriorityActivityCard: {
    borderLeftWidth: 4,
    borderLeftColor: theme.error,
  },
  priorityIndicator: {
    position: 'absolute',
    top: -5,
    right: -5,
    backgroundColor: theme.error,
    borderRadius: 10,
    width: 20,
    height: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
  timeFilterContainer: {
    flexDirection: 'row',
    marginBottom: 12,
    paddingHorizontal: 16,
  },
  timeFilterButton: {
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 16,
    marginRight: 8,
    backgroundColor: theme.backgroundLight,
  },
  timeFilterButtonActive: {
    backgroundColor: theme.primary,
  },
  timeFilterText: {
    fontSize: 12,
    color: theme.textSecondary,
  },
  timeFilterTextActive: {
    color: 'white',
    fontWeight: '500',
  },
});

// For backwards compatibility, export the light theme styles
export const styles = createHomeStyles(Colors.light);
